[build]
  command = "yarn && yarn build"
  publish = "gnt2-migration-ui/dist"

[build.environment]
  BATCHING_GNT_TOKEN_CONTRACT_ADDRESS_RINKEBY = "0x22f8707c775aEF9243B751F6831B59BfC85A4175"
  NEW_GNT_TOKEN_CONTRACT_ADDRESS_RINKEBY = "0x3D775f0285ce59B470cFb21F82B5C6Aa2B931f16"
  OLD_GNT_TOKEN_CONTRACT_ADDRESS_RINKEBY = "0x5f04440eeBE94581152C1654fF06726043114461"
  GNT_DEPOSIT_CONTRACT_ADDRESS_RINKEBY = "0xD08D7EAd2b8FFA32dcF32754280484F4982c3c4B"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
